<a href="https://colab.research.google.com/github/krishnamurtv1/Codepath/blob/main/CSIT553_class3_1_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSIT 553 Class 3 Exercise: Data Merging

In [6]:
# only run once
!git clone https://github.com/profliuhao/CSIT553.git

fatal: destination path 'CSIT553' already exists and is not an empty directory.

### Instruction
There are two datasets in this assignment:
1. **Energy_Indicators.csv** contains a list of indicators of energy supply and the percentage of renewable electricity production from the United Nations for the year 2013.
2. **Global_GDP.csv** contains countries' GDP from 1960 to 2017 from Wold Bank.

The following cell is set to load above two datasets as DataFrames: **energy** and **gdp**. Please execute it before working on the following questions. The two DataFrames **energy** and **gdp** can be used directly.

In [7]:
# Don't delete this cell
# Execute this cell to import pandas & numpy, and load data to DataFrames.


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

pd.options.display.max_rows = 10
# energy=pd.read_csv('Energy_Indicators.csv')

energy=pd.read_csv('/content/CSIT553/Module_3/CSIT553_class3_1_exercise/Energy_Indicators.csv')

# gdp = pd.read_csv("Global_GDP.csv")

gdp = pd.read_csv("/content/CSIT553/Module_3/CSIT553_class3_1_exercise/Global_GDP.csv")

In [3]:
energy

,Country Name,Energy Supply,Energy Supply per capita,Renewable Percentage
0,Afghanistan,321,10,78.67
1,Albania,102,35,100.00
2,Algeria,1959,51,0.55
3,American Samoa,...,...,0.64
4,Andorra,9,121,88.70
...,...,...,...,...
222,Viet Nam,2554,28,45.32
223,Wallis and Futuna Islands,0,26,0.00
224,Yemen,344,13,0.00
225,Zambia,400,26,99.71
226,Zimbabwe,480,32,52.54

In [8]:
gdp

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.791961e+09,2.498933e+09,2.467704e+09,2.584464e+09,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,1.019053e+10,1.248694e+10,1.593680e+10,1.793024e+10,2.053654e+10,2.026425e+10,2.061610e+10,1.921556e+10,1.946902e+10,2.081530e+10
2,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.417804e+10,7.549239e+10,8.252614e+10,1.040000e+11,1.140000e+11,1.250000e+11,1.270000e+11,1.030000e+11,9.533720e+10,1.240000e+11
3,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.288135e+10,1.204421e+10,1.192695e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322824e+10,1.138693e+10,1.188368e+10,1.303935e+10
4,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.007353e+09,3.660531e+09,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.012914e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.687488e+09,5.653793e+09,5.829934e+09,6.686683e+09,6.500193e+09,7.073420e+09,7.386891e+09,6.439947e+09,6.715487e+09,7.128691e+09
260,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.691085e+10,2.513027e+10,3.090675e+10,3.272642e+10,3.540133e+10,4.041524e+10,4.322858e+10,3.460248e+10,1.821333e+10,NaN
261,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,7.575248e+09,7.972841e+09,8.497830e+09,9.423212e+09,1.037379e+10,1.133417e+10,...,2.870000e+11,2.970000e+11,3.750000e+11,4.170000e+11,3.960000e+11,3.670000e+11,3.510000e+11,3.180000e+11,2.960000e+11,3.490000e+11
262,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,...,1.791086e+10,1.532834e+10,2.026556e+10,2.346010e+10,2.550337e+10,2.804546e+10,2.715063e+10,2.115439e+10,2.095475e+10,2.580867e+10
263,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,...,4.415703e+09,8.621574e+09,1.014186e+10,1.209845e+10,1.424249e+10,1.545177e+10,1.589105e+10,1.630467e+10,1.661996e+10,1.784582e+10

## Exercise 1
Clean the data in the DataFrame **Energy**. The detailed steps are as follows.  
  
#### Steps:   
1. For all the countries which have missing data (e.g., data with '...'), represent them as np.NaN values.
2. Rename the following list of countries:
        "Republic of Korea": "South Korea",
        "United States of America": "United States",
        "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
        "China, Hong Kong Special Administrative Region": "Hong Kong"

In [9]:
energy = energy.replace('...',np.nan)
energy['Country Name'] = energy['Country Name'].replace({
    "Republic of Korea": "South Korea",
    "United States of America": "United States",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "China, Hong Kong Special Administrative Region": "Hong Kong"
})
energy

,Country Name,Energy Supply,Energy Supply per capita,Renewable Percentage
0,Afghanistan,321,10,78.67
1,Albania,102,35,100.00
2,Algeria,1959,51,0.55
3,American Samoa,NaN,NaN,0.64
4,Andorra,9,121,88.70
...,...,...,...,...
222,Viet Nam,2554,28,45.32
223,Wallis and Futuna Islands,0,26,0.00
224,Yemen,344,13,0.00
225,Zambia,400,26,99.71
226,Zimbabwe,480,32,52.54

####  Execute the following statements
1. Because of '...' in the original data, the columns 'Energy Supply' and 'Energy Supply per capita' are recognized as strings. Use **astype** to convert them to be floating point number.
2. "Energy Supply" is in petajoules but "Energy Supply per capita" is in gigajoules. Convert the "Energy Supply" to gigajoules (there are 1,000,000 gigajoules in a petajoule).

In [10]:
energy['Energy Supply'] = energy['Energy Supply'].astype(float)
energy['Energy Supply per capita'] = energy['Energy Supply per capita'].astype(float)
energy["Energy Supply"] = energy["Energy Supply"]*1000000

## Exercise 2
Process the DataFrame **gdp**. The detailed steps are as follows.  
  
#### Steps:   
1. Rename the following list of countries in "Country Name":
        "Korea, Rep.": "South Korea",
        "Iran, Islamic Rep.": "Iran",
        "Hong Kong SAR, China": "Hong Kong"
2. Copy the column "Country Name" and the last 5 years (2013-2017) of GDP data to the DataFrame **GDP**.

In [14]:
gdp['Country Name'] = gdp['Country Name'].replace({
    "Korea, Rep.": "South Korea",
    "Iran, Islamic Rep.": "Iran",
    "Hong Kong SAR, China": "Hong Kong"
})

GDP = gdp[['Country Name', '2013', '2014', '2015', '2016', '2017']]
GDP

,Country Name,2013,2014,2015,2016,2017
0,Aruba,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,2.026425e+10,2.061610e+10,1.921556e+10,1.946902e+10,2.081530e+10
2,Angola,1.250000e+11,1.270000e+11,1.030000e+11,9.533720e+10,1.240000e+11
3,Albania,1.277628e+10,1.322824e+10,1.138693e+10,1.188368e+10,1.303935e+10
4,Andorra,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.012914e+09
...,...,...,...,...,...,...
259,Kosovo,7.073420e+09,7.386891e+09,6.439947e+09,6.715487e+09,7.128691e+09
260,"Yemen, Rep.",4.041524e+10,4.322858e+10,3.460248e+10,1.821333e+10,NaN
261,South Africa,3.670000e+11,3.510000e+11,3.180000e+11,2.960000e+11,3.490000e+11
262,Zambia,2.804546e+10,2.715063e+10,2.115439e+10,2.095475e+10,2.580867e+10
263,Zimbabwe,1.545177e+10,1.589105e+10,1.630467e+10,1.661996e+10,1.784582e+10

In [16]:
energyGDP2 = energy.merge(GDP, on="Country Name")
energyGDP2

,Country Name,Energy Supply,Energy Supply per capita,Renewable Percentage,2013,2014,2015,2016,2017
0,Afghanistan,3.210000e+08,10.0,78.67,2.026425e+10,2.061610e+10,1.921556e+10,1.946902e+10,2.081530e+10
1,Albania,1.020000e+08,35.0,100.00,1.277628e+10,1.322824e+10,1.138693e+10,1.188368e+10,1.303935e+10
2,Algeria,1.959000e+09,51.0,0.55,2.100000e+11,2.140000e+11,1.660000e+11,1.590000e+11,1.700000e+11
3,American Samoa,NaN,NaN,0.64,6.410000e+08,6.430000e+08,6.590000e+08,6.580000e+08,NaN
4,Andorra,9.000000e+06,121.0,88.70,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.012914e+09
...,...,...,...,...,...,...,...,...,...
180,Uruguay,1.960000e+08,58.0,71.61,5.753123e+10,5.723601e+10,5.327430e+10,5.268761e+10,5.615697e+10
181,Uzbekistan,1.798000e+09,62.0,21.33,5.769045e+10,6.306708e+10,6.690380e+10,6.706757e+10,4.871769e+10
182,Vanuatu,3.000000e+06,10.0,14.71,8.017876e+08,8.149543e+08,7.379172e+08,7.879426e+08,8.628798e+08
183,Zambia,4.000000e+08,26.0,99.71,2.804546e+10,2.715063e+10,2.115439e+10,2.095475e+10,2.580867e+10
184,Zimbabwe,4.800000e+08,32.0,52.54,1.545177e+10,1.589105e+10,1.630467e+10,1.661996e+10,1.784582e+10

## Exercise 3
 Create a new DataFrame **energyGDP** to merge the dataset **energy** and **GDP**.Set the column "Country Name" to be the index of **energyGDP**.
  
#### Steps:   
1. Merge **energy** and **GDP** with the key "Country Name".
2. Set the column "Country Name" to be the index of **energyGDP**.

In [19]:
energyGDP = pd.merge(energy, GDP, on='Country Name')
energyGDP = energyGDP.set_index('Country Name')
energyGDP

,Energy Supply,Energy Supply per capita,Renewable Percentage,2013,2014,2015,2016,2017
Country Name,,,,,,,,
Afghanistan,3.210000e+08,10.0,78.67,2.026425e+10,2.061610e+10,1.921556e+10,1.946902e+10,2.081530e+10
Albania,1.020000e+08,35.0,100.00,1.277628e+10,1.322824e+10,1.138693e+10,1.188368e+10,1.303935e+10
Algeria,1.959000e+09,51.0,0.55,2.100000e+11,2.140000e+11,1.660000e+11,1.590000e+11,1.700000e+11
American Samoa,NaN,NaN,0.64,6.410000e+08,6.430000e+08,6.590000e+08,6.580000e+08,NaN
Andorra,9.000000e+06,121.0,88.70,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.012914e+09
...,...,...,...,...,...,...,...,...
Uruguay,1.960000e+08,58.0,71.61,5.753123e+10,5.723601e+10,5.327430e+10,5.268761e+10,5.615697e+10
Uzbekistan,1.798000e+09,62.0,21.33,5.769045e+10,6.306708e+10,6.690380e+10,6.706757e+10,4.871769e+10
Vanuatu,3.000000e+06,10.0,14.71,8.017876e+08,8.149543e+08,7.379172e+08,7.879426e+08,8.628798e+08
Zambia,4.000000e+08,26.0,99.71,2.804546e+10,2.715063e+10,2.115439e+10,2.095475e+10,2.580867e+10
Zimbabwe,4.800000e+08,32.0,52.54,1.545177e+10,1.589105e+10,1.630467e+10,1.661996e+10,1.784582e+10

### Exercise 4
Create two new columns in energeGDP.

Steps:
1. Create a new column called "Mean GDP" which records the average GDP in the last 5 years (2013-2017).
2. Create a new column called "E2GRatio" which records the ratio of "Energy Supply" to "Mean GDP".

In [21]:
energyGDP['Mean GDP'] = energyGDP[['2013', '2014', '2015', '2016', '2017']].mean(axis=1)
energyGDP['E2GRatio'] = energyGDP['Energy Supply']/energyGDP['Mean GDP']
energyGDP

,Energy Supply,Energy Supply per capita,Renewable Percentage,2013,2014,2015,2016,2017,Mean GDP,E2GRatio
Country Name,,,,,,,,,,
Afghanistan,3.210000e+08,10.0,78.67,2.026425e+10,2.061610e+10,1.921556e+10,1.946902e+10,2.081530e+10,2.007605e+10,0.015989
Albania,1.020000e+08,35.0,100.00,1.277628e+10,1.322824e+10,1.138693e+10,1.188368e+10,1.303935e+10,1.246290e+10,0.008184
Algeria,1.959000e+09,51.0,0.55,2.100000e+11,2.140000e+11,1.660000e+11,1.590000e+11,1.700000e+11,1.838000e+11,0.010658
American Samoa,NaN,NaN,0.64,6.410000e+08,6.430000e+08,6.590000e+08,6.580000e+08,NaN,6.502500e+08,NaN
Andorra,9.000000e+06,121.0,88.70,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.012914e+09,3.066807e+09,0.002935
...,...,...,...,...,...,...,...,...,...,...
Uruguay,1.960000e+08,58.0,71.61,5.753123e+10,5.723601e+10,5.327430e+10,5.268761e+10,5.615697e+10,5.537723e+10,0.003539
Uzbekistan,1.798000e+09,62.0,21.33,5.769045e+10,6.306708e+10,6.690380e+10,6.706757e+10,4.871769e+10,6.068932e+10,0.029626
Vanuatu,3.000000e+06,10.0,14.71,8.017876e+08,8.149543e+08,7.379172e+08,7.879426e+08,8.628798e+08,8.010963e+08,0.003745
Zambia,4.000000e+08,26.0,99.71,2.804546e+10,2.715063e+10,2.115439e+10,2.095475e+10,2.580867e+10,2.462278e+10,0.016245
Zimbabwe,4.800000e+08,32.0,52.54,1.545177e+10,1.589105e+10,1.630467e+10,1.661996e+10,1.784582e+10,1.642265e+10,0.029228